version: 0.2

phases:
    pre_build:
        commands:
            ### Login to Amazon ECR
             - echo Logging in to Amazon ECR...
             - echo $(aws --version)
             - podman --version
             - which aws
             - which podman
             - env
             - aws ecr get-login-password --region us-west-2  > ecr_passwd.txt
             - podman login --username AWS --password-stdin 140023371661.dkr.ecr.us-west-2.amazonaws.com < ecr_passwd.txt
            ### Pulling the image
             - echo Pulling latest image from Docker Hub
             - podman pull $IMAGE_REPO_NAME:$IMAGE_TAG
            ### Creating the ECR repository
             ###- echo Create Repo $(/usr/local/bin/aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} || /usr/local/bin/aws ecr create-repository --repository-name ${IMAGE_REPO_NAME})
    build:
        commands:
            ### Building the image 
             - echo Build started on `date`
             - podman tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
             - echo Build completed on `date`
    post_build:
        commands:
            ### Publish the docker image to ECR
            - echo Pushing the Docker image...
            - podman push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
